### ISSUE TITLE
Lists and Tasks

### ISSUE THREAD

**Issue by allisonanne** [SIU-CS-435/RARE-production#1]
As a user I want to create a list and add to-dos so that I can keep my tasks organized.

1. User created list and given option to add tasks to list.
2. User named list.
3. User created a task in a list.
4. User named a task.

**Comment by ethanx94** [comment]
Todo implement:
multiple lists per user,
ability to name/rename lists,
ability to name/rename tasks

**Comment by ethanx94** [comment]
Phase 1:
Upon login, populate table with corresponding userID's tasks

Phase 2:
Upon login, show userID's lists, select a list, populate table with corresponding userID's tasks

**Comment by ethanx94** [comment]
Codebehind (.cs) variables can be accessed like the following:
This is how I'm getting the user's email and I'll use it in the select statement, where clause so that it will only fetch tasks pertaining to the current user that is logged in.
```
public string userid = HttpContext.Current.User.Identity.Name;

protected void Page_Load(object sender, EventArgs e)
{
      this.DataBind();
}
```
```
<asp:Label ID="User" runat="server" Text='<%# userid %>'></asp:Label>
```
