### ISSUE TITLE
Admin Panel

### ISSUE THREAD

**Issue by allisonanne** [SIU-CS-435/RARE-production#10]
As the admin I want to manage user data so that I can delete users when necessary.

1. User can be deleted by admin.
2. User receives notification that they have been deleted.

**Comment by ethanx94** [comment]
Make a new page AdminPanel.aspx (Could be a copy of UserTaskList.aspx)
Populate a GridView with the AspUsers table from database.
Click generate delete buttons when you set up the database source.
Before the delete statement is executed plug in SendGrid code to email them that they have been deleted.
