### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by allisonanne** [SIU-CS-435/RARE-production#12]
As a user I want to login so that I can view my own lists and tasks.

1. User’s information is validated based on the login fields.
2. User provided “Remember Me” checkbox with cookie.
3. User provided “Login Failure” message after incorrect information entered.
4. User provided captcha prompt after 3x failure.

**Comment by ethanx94** [comment]
Look into session state 
Session.Contents[0]
Use this for retrieving individual user databases
