### ISSUE TITLE
Formatting: Login Modal has offset text at certain resolutions

### ISSUE THREAD

**Issue by ethanx94** [SIU-CS-435/RARE-production#28]
When resizing the browser window I notice the email text is offset on the popup login bootstrap modal. Should be a quick fix as the password text does not offset. See the attached screenshot
<img width="1280" alt="untitled" src="https://cloud.githubusercontent.com/assets/4449468/14729842/dfae4acc-0806-11e6-874e-429069042c38.png">

**Comment by allisonanne** [comment]
I'm going to remove the login/registration buttons entirely. It isn't worth fixing bugs on this when we have a functional login/registration in the upper right hand corner
