### ISSUE TITLE
Prioritize

### ISSUE THREAD

**Issue by allisonanne** [SIU-CS-435/RARE-production#3]
As a user I want to set priorities for tasks so that I can view what task is most important at a given time.

1. User set a task’s priority. 
2. User views tasks. organized by priority. 
3. User modifies priorities.

**Comment by ethanx94** [comment]
Priority could be ideally modified by a DropDown list in the GridView that appears after Edit is pressed. I had tried this previously and hit some kinks.
GridView has the ability to sort by priority (or any field of a GridView) on the column itself by clicking. This is really easy to enable if it hasn't been already.
We may want to filter by a specific priority.
