### ISSUE TITLE
Deadline whitespace bug on repeat

### ISSUE THREAD

**Issue by eastcoastcoder** [SIU-CS-435/RARE-production#38]
With the new method of resolving the deadline, it grabs the text within the deadline cell as a string (referenced through an array index). If the deadline for a task is empty and you hit repeat, it will instead put the symbol for a non-breaking space (&nbsp;). This is a common issue and I've searched around and found various ways to correct it. However, even leaving the correctional code in, it appears to do nothing. Possibly the index is not allowed to be reassigned. Using a separate variable for the insert statement instead doesn't work either.

Reproduce By:
- Adding a new task with no deadline
- Hitting the repeat button

**Comment by Griffon0129** [comment]
It's now required to put something in for deadline which fixes this.
