### ISSUE TITLE
Repeat

### ISSUE THREAD

**Issue by allisonanne** [SIU-CS-435/RARE-production#4]
As a user I want to repeat tasks so that I can save time by not having to recreate tasks.

1.  User selects which task to repeat.
2. User views repeated task on their list.
3. User moves repeated task to a different list.

**Comment by ethanx94** [comment]
Add column to GridView, containing a Repeat button.
Repeat will run the same INSERT statement that a new task would run, however it will get it's data from the current row. (This might take some figuring out)

**Comment by ethanx94** [comment]
Something like this to grab individual cells from each column in a row.
```
if (e.Row.RowType == DataControlRowType.DataRow){
     string insertCommand = "Insert into [dbo].[" + curUser + "] ([task], [priority], [progress], [end], [deadline]) Values('" + e.Row.Cells[0].Text + "', " + e.Row.Cells[1].Text + ", " + e.Row.Cells[2].Text + ", " + e.Row.Cells[3].Text + ", " + e.Row.Cells[4].Text + ");";
}
```
